version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'creole'
